### PR TITLE
Package according modern guidelines

### LINKED ISSUE #31: It is not possible to install package in virtualenv if system environment has no spacy installed
It is not possible to install the package in virtualenv when `spacy`  not installed in system environment, because `setup.py` imported all project modules indirectly through importing `__init__.py`:
```
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install .
Processing /home/rominf/dev/spacy_conll
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-tbqma0n0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-tbqma0n0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-tbqma0n0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-tbqma0n0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
        File "/home/rominf/dev/spacy_conll/spacy_conll/__init__.py", line 3, in <module>
          from .formatter import ConllFormatter
        File "/home/rominf/dev/spacy_conll/spacy_conll/formatter.py", line 5, in <module>
          from spacy.language import Language
      ModuleNotFoundError: No module named 'spacy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

I am working on this.

### PR DESCRIPTION
**Pull request by rominf**
# What does this PR do?

See commit messages and linked issue for more details.

- **Package according modern guidelines**
- **Automatic reformatting**
- **Address flake8 errors**

Fixes #31

## Before submitting, make sure that you can tick all these boxes.

- [x] Did you read the [contributor guideline](../CONTRIBUTING.md)?
- [ ] Is your PR against the `dev` branch?
      `dev` branch is out-of-date, hence using `master`.
- [ ] Did you write any new necessary tests for testing new functionality?
      Not applicable.
- [ ] Did you write comprehensive documentation/docstrings (if applicable)?
      Not applicable.
- [x] Did you successfully run the tests with `pytest tests/`?
- [x] Did you ensure a consistent style with `make style` and `make quality`

### CODE REVIEW

**Comment by rominf** [comment]
Hi @BramVanroy! Could you please have a look?

**Comment by BramVanroy** [comment]
> Hi @BramVanroy! Could you please have a look?

Hi there! You're definitely right that this package could use a refactor and bump to new standards. We can/should probably also deprecate support for earlier python versions that are approaching EOL. 

That said, I'm not a hatchling person (just setuptools works best for me) so I rather not merge this as it is now. If you can refactor to use plain setuptools (example: https://github.com/BramVanroy/dutch-instruction-datasets/) I can reconsider. Or I can do it over summer if you can wait that long.

Thanks

**Comment by rominf** [comment]
I replaced hatch(ling) with setuptools as you suggested and updated Python versions. Also, I moved source to `src` as per example. I hesitated whether to move black configuration to `pyproject.toml` or not. I kept it in Makefile, but I am open moving it to `pyproject.toml``.

**Comment by rominf** [comment]
Hi @BramVanroy! Is there something else I need to do here so that you reconsider?

**Pull request merged**
