### PR TITLE
Parse conllu 2 spacy object

### LINKED ISSUE #11: Can I read conll format and turn it to spacy object?
Can I take a conll format file and transform it in to spacy object using the repo code?
lets say I have the following file: 

      # sent_id = 9
      # text = היא אמרה כי שירות התעסוקה הציע להביא עובדים מדרום לבנון, אך תנועת המושבים סירבה.
      1	היא	הוא	PRON	PRON	Gender=Fem|Number=Sing|Person=3|PronType=Prs	2	nsubj	_	_
      2	אמרה	אמר	VERB	VERB	Gender=Fem|HebBinyan=PAAL|Number=Sing|Person=3|Tense=Past|Voice=Act	0	root	_	_
      3	כי	כי	SCONJ	SCONJ	_	7	mark	_	_
      4	שירות	שירות	NOUN	NOUN	Definite=Cons|Gender=Masc|Number=Sing	7	nsubj	_	_
      5-6	התעסוקה	_	_	_	_	_	_	_	_
      5	ה	ה	DET	DET	Definite=Def|PronType=Art	6	det	_	_
      6	תעסוקה	תעסוקה	NOUN	NOUN	Gender=Fem|Number=Sing	4	compound:smixut	_	_
      7	הציע	הציע	VERB	VERB	Gender=Masc|HebBinyan=HIFIL|Number=Sing|Person=3|Tense=Past|Voice=Act	2	ccomp	_	_
      8	להביא	הביא	VERB	VERB	HebBinyan=HIFIL|VerbForm=Inf|Voice=Act	7	xcomp	_	_
      9	עובדים	עובד	NOUN	NOUN	Gender=Masc|Number=Plur	8	obj	_	_
      10-11	מדרום	_	_	_	_	_	_	_	_
      10	מ	מ	ADP	ADP	_	11	case	_	_
      11	דרום	דרום	NOUN	NOUN	Definite=Cons|Gender=Masc|Number=Sing	8	obl	_	_
      12	לבנון	לבנון	PROPN	PROPN	_	11	compound:smixut	_	SpaceAfter=No
      13	,	,	PUNCT	PUNCT	_	18	punct	_	_
      14	אך	אך	CCONJ	CCONJ	_	18	cc	_	_
      15	תנועת	תנועה	NOUN	NOUN	Definite=Cons|Gender=Fem|Number=Sing	18	nsubj	_	_
      16-17	המושבים	_	_	_	_	_	_	_	_
      16	ה	ה	DET	DET	Definite=Def|PronType=Art	17	det	_	_
      17	מושבים	מושב	NOUN	NOUN	Gender=Masc|Number=Plur	15	compound:smixut	_	_
      18	סירבה	סירב	VERB	VERB	Gender=Fem|HebBinyan=PIEL|Number=Sing|Person=3|Tense=Past|Voice=Act	7	conj	_	SpaceAfter=No
      19	.	.	PUNCT	PUNCT	_	2	punct	_	_

Can I somehow use the code to read the format as spacy doc?

### PR DESCRIPTION
**Pull request by shaked571**
Not sure if the code fit to the repo standart, the making of the spacy object is abit complex.  and it supports only  files and not strings because this is how you will usually use it. closes #11

### CODE REVIEW

**Comment by BramVanroy** [comment]
I have pushed quite some big changes. I hope that that is alright with you @shaked571. Most important ones:

- do not support MWT or empty nodes
- raise errors where appropriate
- include morph
- use Doc() constructor more widely
- instead of generator, return one Doc per CoNLL file
- set custom extension for properties that CoNLL supports but spaCy does not (dep graph, misc)
- set custom properties for the metadata

closes #14

**Comment by shaked571** [comment]
closes #11

**Comment by shaked571** [comment]
I'm not sure what you meant by

> Can you add "closes #11" to your PR message so that the issue closes automatically

**Comment by BramVanroy** [comment]
> I'm not sure what you meant by
> 
> > Can you add "closes #11" to your PR message so that the issue closes automatically

If you add "closes #11" in the FIRST post of this PR, the issue that you posted (#11) will close automatically and marked as solved as soon as this PR is merged.

**Comment by BramVanroy** [comment]
Hi @shaked571

Can you do the PR against `dev` branch instead of master? Thanks

**Comment by BramVanroy** [comment]
Thanks a lot @shaked571! I'll try to rework some things on dev and push a new release in the following weeks.

**Comment by shaked571** [comment]
Sure thing, happy to help. And in the end you did the heavy lifting ;)
You had great changes.
🥂

**Pull request merged**
